# This workflow will check that the code version was increased.
#
# Copyright (c) 2022 MeteoSwiss, created by F.P.A. Vogt; frederic.vogt@meteoswiss.ch

name: CI_pypi

on:
  release:
    types: [published]
  pull_request:
    branches: [ master, develop ]

jobs:
  pypi:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependancies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install wheel
      shell: bash

    - name: Build distribution
      run: |
        python setup.py sdist bdist_wheel
      shell: bash
