# This workflow will push the code onto pypi.
# It uses the PYPI_USERNAME and PYPI_PASSWORD secrets from GITHUB to login on there.
#
# Copyright (c) 2022 MeteoSwiss, created by F.P.A. Vogt; frederic.vogt@meteoswiss.ch

name: CI_pypi

on:
  release:
    types: [published]

jobs:
  pypi:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependancies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install wheel
        pip install twine
      shell: bash

    - name: Build the wheels
      run: |
        python setup.py sdist bdist_wheel
      shell: bash

    - name: Deploy to testpypi
      # Let's make use of Github secrest at the repo level to avoid spelling out secret stuff
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PWD: ${{ secrets.PYPI_PASSWORD }}
      # After assembling the distribution, we first go to testpypi to make sure nothing blows up
      # Only then do we push to pypi
      run: |
        twine upload -r testpypi dist/* --verbose --skip-existing -u "$PYPI_USERNAME" -p "$PYPI_PWD"
      shell: bash

    - name: Deploy to pypi
      # Let's make use of Github secrest at the repo level to avoid spelling out secret stuff
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PWD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/* --verbose --skip-existing -u "$PYPI_USERNAME" -p "$PYPI_PWD"
      shell: bash
